Connect back to master at 169.230.90.31:50280 with ID 0:PNDMPIWD
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/shruthi/imp-clean/build/lib/IMP/parallel/slave_handler.py", line 89, in main
    h.run()
  File "/home/shruthi/imp-clean/build/lib/IMP/parallel/slave_handler.py", line 49, in run
    self._handle_network_io(master)
  File "/home/shruthi/imp-clean/build/lib/IMP/parallel/slave_handler.py", line 74, in _handle_network_io
    setup_args = obj.obj()
TypeError: 'tuple' object is not callable
